name: id
version: 1.1.0
description: A simple plugin to display item data
author: KarlTheBee
website : github.com/karlthebee/spigot.id
main: de.karlthebee.spigot.id.ID

commands:
  id:
    descrption: shows id data
    usage: /id <args>
    permission: id.id
  idoff:
    description: shows offhand data
    usage: /idoff <args>
    permission: id.off
  idblock:
    description: shows block data
    usage: /idblock <args>
    permission: id.block
  idall:
    description: shows hand, off hand and block data
    usage: /idall <args>
    permission: id.all

permission:
  id.id:
    descrption: allows showing basic info
  id.off:
    descrition: allows showing off hand info
  id.block:
    descrition: allows showing block info
  id.all:
    descrition: allows showing hand, offhand and block info
